[workspace]
members = [
    "storage-service",
]
exclude = [
    "jetcache-client",
]
resolver = "3"

[workspace.package]
edition = "2021"
version = "2.0.0-rc.1"
authors = ["Taika 3D Oy"]
repository = "https://github.com/Taika-3D-Oy/jetcache"
description = "In-memory read-through cache backed by NATS JetStream KV"
license = "Apache-2.0"

[workspace.dependencies]
wasip3 = { version = "0.7", features = ["async-spawn"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"



[profile.release]
lto = "thin"
opt-level = "s"
strip = true
